DATA SECTION
;
KEY DD 'PING'
TODECRYPT DB 'IM GONNA BE DECRYPTEDIM GONNA BE DECRYPTEDIM GONNA BE DECRYPTEDIM GONNA BE DECRYPTED'
;
CODE SECTION
;
START:
MOV ESI, [KEY]
MOV EDI, ADDR TODECRYPT
MOV ECX, 0
LOOP:
XOR [EDI], ESI
INC ECX
CMP ECX, 0x100000
JNZ LOOP
RET
